baseURL: "https://billhennessy.com"
languageCode: "en-us"
title: "Bill Hennessy"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  gab: "https://gab.com/whennessy"
  github: "https://github.com/billhennessy"

taxonomies:
  author: authors
